### PR TITLE
Opinionated styling, package and code updates

### PR DESCRIPTION
**Pull request by TheLartians**
Hey, thanks for this great template! It really helped me get started with Chrome extensions. Doing so, I've made a few adjustments to the starter that make it much more usable for me. I was wondering if some of these changes could be interesting for the original template as well.

I know that these are very opinionated changes, so feel free to simply ignore/close the PR if you are not interested. I could also split anything you find interesting into separate PRs, if you prefer.

## Summary of changes

- Switch from _npm_ to _yarn_
- Switch from _jQuery_ to _React_
- Add [auto reload capability](https://github.com/xpl/crx-hotreload#readme) (should also address #18)
- Add _prettier_ to enforce code styling
- Remove the _moment_ package in favour of the JS's built-in `Date` class 
- Switch from _Travis CI_ to _GitHub Workflows_
- Run tests and check style in CI
- Inline the example `sum.ts` file into the example test, as it's not used for anything else
- Enable `strict` mode and allow compiling with errors (TS correctness will be checked in CI)
- Remove polling background script to prevent accidental console spamming
- Add [a new svg logo](https://raw.githubusercontent.com/TheLartians/chrome-extension-typescript-starter/master/resources/export/icon.svg) for the project, from which the extension icons are automatically generated in 128px, 48px and 16px resolution
- Update the [Readme](https://github.com/TheLartians/chrome-extension-typescript-starter/blob/master/README.md) to feature the new logo
- Remove `.vscode/tasks.json` as _vscode_ will [automatically detect tasks](https://code.visualstudio.com/docs/editor/tasks#_task-autodetection) from `package.json`

### CODE REVIEW

**Comment by chibat** [comment]
Thanks for your PR.
I will refer to it and try to incorporate it partially.

**Comment by LazyCompiler** [comment]
Very useful change! 
A worth mentioning thing is that the script "prepare": "./prepare_icons.sh" use the command **convert** which is part of **ImageMagick**, so make sure you guys install it before (_brew install imagemagick_).

**Comment by chibat** [comment]
@TheLartians 
I would be grateful if you could create another new PR for the following changes.
- Switch from _jQuery_ to _React_
- Remove the _moment_ package in favour of the JS's built-in `Date` class

**Comment by TheLartians** [comment]
Sure, I'll create the new PR later today!

**Pull request closed without merging**
